version: "3"

services:

  postgres-users-dev:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD:mysecretpassword
      - POSTGRES_HOST_AUTH_METHOD=trust
